/**
 * File: AccountGUI.java
 * Desc: Sends input to AccountController and handles all
 *       the GUI related events
 *
 * Author: Pat Ripley
 */
package webradio;

// imports
import java.awt.Color;
import java.awt.event.*;
import javax.swing.*;

public class AccountGUI extends javax.swing.JFrame {

    public class ListElement {

        String username, password, name;
        int access;

        public ListElement(String username, String password, int access, String name) {
            this.username = username;
            this.password = password;
            this.access = access;
            this.name = name;
        }

        @Override
        public String toString() {
            return username;
        }
    }

    // ivars
    Account temp;                                                   // used for editing
    DefaultListModel<ListElement> users = new DefaultListModel<>();      // for the graphical list
    ListElement[] elements;
    boolean apasswordsMatch = true;
    boolean spasswordsMatch = true;

    public static final int ADMIN = 0;
    public static final int MOD = 1;
    public static final int USER = 2;

    public static final int ADD = 0;
    public static final int REMOVE = 1;

    /**
     * Creates new form AccountGUI
     */
    public AccountGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        searchPanel = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        sUField = new javax.swing.JTextField();
        spassField = new javax.swing.JPasswordField();
        sconfirmpassField = new javax.swing.JPasswordField();
        spasswordMatch = new javax.swing.JLabel();
        sshowPassword = new javax.swing.JLabel();
        sAField = new javax.swing.JTextField();
        sAComboBox = new javax.swing.JComboBox<>();
        sNField = new javax.swing.JTextField();
        addPanel = new javax.swing.JPanel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        L10 = new javax.swing.JLabel();
        ashowPassword = new javax.swing.JLabel();
        aUField = new javax.swing.JTextField();
        apassField = new javax.swing.JPasswordField();
        aconfirmpassField = new javax.swing.JPasswordField();
        apasswordMatch = new javax.swing.JLabel();
        aAField = new javax.swing.JTextField();
        aAComboBox = new javax.swing.JComboBox<>();
        aNField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        errLabel = new javax.swing.JLabel();
        scrollpane = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        closeItem = new javax.swing.JMenuItem();
        logoutItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        bugItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("W.R.A.P. - Users");
        setIconImage(new ImageIcon("src\\images\\imageicon.png").getImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tabs.setFocusable(false);
        tabs.setName("tabPane"); // NOI18N

        deleteButton.setText("Delete");
        deleteButton.setEnabled(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.setEnabled(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.setEnabled(false);
        submitButton.setMaximumSize(new java.awt.Dimension(68, 23));
        submitButton.setMinimumSize(new java.awt.Dimension(68, 23));
        submitButton.setPreferredSize(new java.awt.Dimension(68, 23));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        L1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L1.setText("Username:");

        L2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L2.setText("Password:");

        L3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L3.setText("Confirm:");

        L4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L4.setText("Access:");

        L5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L5.setText("Name:");

        sUField.setEditable(false);
        sUField.setFocusCycleRoot(true);
        sUField.setNextFocusableComponent(spassField);
        sUField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sUFieldFocusGained(evt);
            }
        });

        spassField.setEditable(false);
        spassField.setNextFocusableComponent(sconfirmpassField);
        spassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spassFieldFocusGained(evt);
            }
        });
        spassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spassFieldKeyReleased(evt);
            }
        });

        sconfirmpassField.setEditable(false);
        sconfirmpassField.setNextFocusableComponent(aAComboBox);
        sconfirmpassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sconfirmpassFieldFocusGained(evt);
            }
        });
        sconfirmpassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sconfirmpassFieldKeyReleased(evt);
            }
        });

        spasswordMatch.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        spasswordMatch.setText(" ");

        sshowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        sshowPassword.setToolTipText("");
        sshowPassword.setEnabled(false);
        sshowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sshowPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sshowPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sshowPasswordMouseExited(evt);
            }
        });

        sAField.setEditable(false);
        sAField.setEnabled(false);

        sAComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 : Admin", "1 : Mod", "2 : User", "--" }));
        sAComboBox.setSelectedIndex(3);
        sAComboBox.setToolTipText("");
        sAComboBox.setEnabled(false);
        sAComboBox.setName(""); // NOI18N
        sAComboBox.setNextFocusableComponent(sNField);
        sAComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAComboBoxActionPerformed(evt);
            }
        });

        sNField.setEditable(false);
        sNField.setNextFocusableComponent(sUField);
        sNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sNFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(editButton)
                        .addGap(5, 5, 5)
                        .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(L4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(L2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(L3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sNField)
                            .addComponent(sUField)
                            .addComponent(spassField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addComponent(spasswordMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sshowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sconfirmpassField)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                                .addComponent(sAField, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sUField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L2)
                    .addComponent(spassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sconfirmpassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L3))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spasswordMatch)
                    .addComponent(sshowPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(editButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        tabs.addTab("Search", searchPanel);

        addPanel.setFocusable(false);

        L6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L6.setText("Username:");

        L7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L7.setText("Password:");

        L8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L8.setText("Access:");

        L9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L9.setText("Name:");

        L10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        L10.setText("Confirm:");

        ashowPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        ashowPassword.setToolTipText("");
        ashowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ashowPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ashowPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ashowPasswordMouseExited(evt);
            }
        });

        aUField.setFocusCycleRoot(true);
        aUField.setNextFocusableComponent(apassField);
        aUField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aUFieldFocusGained(evt);
            }
        });
        aUField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aUFieldKeyPressed(evt);
            }
        });

        apassField.setNextFocusableComponent(aconfirmpassField);
        apassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                apassFieldFocusGained(evt);
            }
        });
        apassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apassFieldKeyReleased(evt);
            }
        });

        aconfirmpassField.setNextFocusableComponent(aAComboBox);
        aconfirmpassField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aconfirmpassFieldFocusGained(evt);
            }
        });
        aconfirmpassField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aconfirmpassFieldKeyReleased(evt);
            }
        });

        apasswordMatch.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        apasswordMatch.setText(" ");

        aAField.setEditable(false);
        aAField.setBackground(new java.awt.Color(255, 255, 255));

        aAComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 : Admin", "1 : Mod", "2 : User", "--" }));
        aAComboBox.setSelectedIndex(3);
        aAComboBox.setName(""); // NOI18N
        aAComboBox.setNextFocusableComponent(aNField);
        aAComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aAComboBoxActionPerformed(evt);
            }
        });
        aAComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aAComboBoxKeyPressed(evt);
            }
        });

        aNField.setNextFocusableComponent(aUField);
        aNField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aNFieldFocusGained(evt);
            }
        });
        aNField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                aNFieldKeyPressed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(L7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L6, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(L8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(L9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aNField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                                    .addComponent(apasswordMatch, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ashowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(aconfirmpassField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(addPanelLayout.createSequentialGroup()
                                    .addComponent(aAField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(aAComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(apassField)
                                .addComponent(aUField)))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aUField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L7)
                    .addComponent(apassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aconfirmpassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L10))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apasswordMatch)
                    .addComponent(ashowPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aAComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L8)
                    .addComponent(aAField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addGap(23, 23, 23))
        );

        tabs.addTab("Add", addPanel);

        errLabel.setForeground(new java.awt.Color(255, 0, 0));
        errLabel.setText(" ");

        list.setModel(FillList());
        list.setFocusable(false);
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        scrollpane.setViewportView(list);

        file.setText("File");

        closeItem.setText("Close");
        closeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeItemActionPerformed(evt);
            }
        });
        file.add(closeItem);

        logoutItem.setText("Logout");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        file.add(logoutItem);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        file.add(exitItem);

        menubar.add(file);

        help.setText("Help");

        bugItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bug_PNG3980.png"))); // NOI18N
        bugItem.setText("Report a bug");
        bugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugItemActionPerformed(evt);
            }
        });
        help.add(bugItem);

        menubar.add(help);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpane)
                    .addComponent(tabs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles the AddButton pressed Checks to see if all fields are filled,
     * then adds
     *
     * @param evt
     */
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if (aCheck()) {
            Add();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Main.CloseAccountGUI();
    }//GEN-LAST:event_formWindowClosed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int res = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to delete user "
                + sUField.getText() + "?",
                "Confirm Deletion",
                JOptionPane.YES_NO_OPTION);
        switch (res) {
            case 0:
                Delete();
                break;
            default:
            // do nothing
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (sCheck()) {
            Submit();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        Edit();
    }//GEN-LAST:event_editButtonActionPerformed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        if (!users.isEmpty()) {
            submitButton.setEnabled(false);
            editButton.setEnabled(true);
            deleteButton.setEnabled(true);
            setSearchFieldsEditable(false);

            Search(users.elementAt(list.getSelectedIndex()).username);
            tabs.setSelectedIndex(0);
            sCheckPasswordMatch();
        } else {
            // do nothing
            // it crashes otherwise
        }
    }//GEN-LAST:event_listMouseClicked

    private void aUFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aUFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_aUFieldKeyPressed

    private void aAComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aAComboBoxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_aAComboBoxKeyPressed

    private void aNFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aNFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_aNFieldKeyPressed

    private void closeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeItemActionPerformed
        Main.CloseAccountGUI();
    }//GEN-LAST:event_closeItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        Main.Logout();
        Main.CloseAccountGUI();
    }//GEN-LAST:event_logoutItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        int res = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to exit WRAP?",
                "",
                JOptionPane.YES_NO_OPTION);
        switch (res) {
            case 0:
                System.exit(0);
                break;
            default:
            // do nothing
        }
    }//GEN-LAST:event_exitItemActionPerformed

    private void bugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugItemActionPerformed
        Main.LaunchBugReportGUI();
    }//GEN-LAST:event_bugItemActionPerformed

    private void sAComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAComboBoxActionPerformed
        switch (sAComboBox.getSelectedIndex()) {
            case 0:
                sAField.setText("Admin");
                break;
            case 1:
                sAField.setText("Mod");
                break;
            case 2:
                sAField.setText("User");
                break;
            case 3:
                sAField.setText("");
                break;
        }
    }//GEN-LAST:event_sAComboBoxActionPerformed

    private void aAComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aAComboBoxActionPerformed
        switch (aAComboBox.getSelectedIndex()) {
            case 0:
                aAField.setText("Admin");
                break;
            case 1:
                aAField.setText("Mod");
                break;
            case 2:
                aAField.setText("User");
                break;
            case 3:
                aAField.setText("");
                break;
        }
    }//GEN-LAST:event_aAComboBoxActionPerformed

    private void ashowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ashowPasswordMouseClicked
        if (apassField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nothing to show here!");
        } else {
            JOptionPane.showMessageDialog(null, apassField.getText());
        }
    }//GEN-LAST:event_ashowPasswordMouseClicked

    private void ashowPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ashowPasswordMouseEntered
        apasswordMatch.setForeground(Color.black);
        apasswordMatch.setText("Show password");
    }//GEN-LAST:event_ashowPasswordMouseEntered

    private void ashowPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ashowPasswordMouseExited
        if (!apassField.getText().equals("") && !aconfirmpassField.getText().equals("")) {
            sCheckPasswordMatch();
        } else {
            apasswordMatch.setText("");
        }
    }//GEN-LAST:event_ashowPasswordMouseExited

    private void sshowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sshowPasswordMouseClicked
        if (spassField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nothing to show here!");
        } else {
            JOptionPane.showMessageDialog(null, spassField.getText());
        }
    }//GEN-LAST:event_sshowPasswordMouseClicked

    private void sshowPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sshowPasswordMouseEntered
        if (sshowPassword.isEnabled()) {
            spasswordMatch.setForeground(Color.black);
            spasswordMatch.setText("Show password");
        }
    }//GEN-LAST:event_sshowPasswordMouseEntered

    private void sshowPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sshowPasswordMouseExited
        if (sshowPassword.isEnabled()) {
            if (!spassField.getText().equals("") && !sconfirmpassField.getText().equals("")) {
                sCheckPasswordMatch();
            } else {
                spasswordMatch.setText("");
            }
        }
    }//GEN-LAST:event_sshowPasswordMouseExited

    private void spassFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spassFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (submitButton.isEnabled()) {
                submitButton.doClick();
            }
        } else {
            sCheckPasswordMatch();
        }
    }//GEN-LAST:event_spassFieldKeyReleased

    private void sconfirmpassFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sconfirmpassFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (submitButton.isEnabled()) {
                submitButton.doClick();
            }
        } else {
            sCheckPasswordMatch();
        }
    }//GEN-LAST:event_sconfirmpassFieldKeyReleased

    private void apassFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apassFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addButton.doClick();
        } else {
            aCheckPasswordMatch();
        }
    }//GEN-LAST:event_apassFieldKeyReleased

    private void aconfirmpassFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aconfirmpassFieldKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addButton.doClick();
        } else {
            aCheckPasswordMatch();
        }
    }//GEN-LAST:event_aconfirmpassFieldKeyReleased

    private void sUFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sUFieldFocusGained
        sUField.selectAll();
    }//GEN-LAST:event_sUFieldFocusGained

    private void spassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spassFieldFocusGained
        spassField.selectAll();
    }//GEN-LAST:event_spassFieldFocusGained

    private void sconfirmpassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sconfirmpassFieldFocusGained
        sconfirmpassField.selectAll();
    }//GEN-LAST:event_sconfirmpassFieldFocusGained

    private void sNFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sNFieldFocusGained
        sNField.selectAll();
    }//GEN-LAST:event_sNFieldFocusGained

    private void aUFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aUFieldFocusGained
        aUField.selectAll();
    }//GEN-LAST:event_aUFieldFocusGained

    private void apassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apassFieldFocusGained
        apassField.selectAll();
    }//GEN-LAST:event_apassFieldFocusGained

    private void aconfirmpassFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aconfirmpassFieldFocusGained
        aconfirmpassField.selectAll();
    }//GEN-LAST:event_aconfirmpassFieldFocusGained

    private void aNFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aNFieldFocusGained
        aNField.selectAll();
    }//GEN-LAST:event_aNFieldFocusGained

    public DefaultListModel FillList() {
        int total = IOController.getTotalUsers();
        Account[] str = IOController.getAllUsers();
        elements = new ListElement[total];

        for (int i = 0; i < total; i++) {
            elements[i] = new ListElement(str[i].getUsername(),
                    str[i].getPassword(),
                    str[i].getAccess(),
                    str[i].getName());
            users.add(i, elements[i]);
        }
        return users;
    }

    public void UpdateList(int action, ListElement element) {
        switch (action) {
            case ADD:         // add
                users.add(users.getSize(), element);
                break;
            case REMOVE:         // remove
                users.remove(list.getSelectedIndex());
                break;
        }
    }

    public void Add() {
        String username = aUField.getText();
        String password = apassField.getText();
        String name = aNField.getText();
        String access = String.valueOf(aAComboBox.getSelectedIndex());

        Account p = new Account(username, password, Integer.valueOf(access), name);
        ListElement element = new ListElement(username, password, Integer.valueOf(access), name);

        if (AccountController.AddUser(p)) {
            errLabel.setForeground(Color.blue);
            errLabel.setText("User added successfully");

            UpdateList(ADD, element);

            setAddValuesToNull();
            aUField.requestFocus();

        } else {
            errLabel.setForeground(Color.red);
            errLabel.setText("Username already taken");
        }
    }

    public void Search(String username) {

        errLabel.setText(" ");

        Account p = AccountController.SearchUser(username);

        editButton.setEnabled(true);
        deleteButton.setEnabled(true);

        setSearchFieldsToValid();

        sUField.setText(p.getUsername());
        spassField.setText(p.getPassword());
        sconfirmpassField.setText(p.getPassword());
        sAField.setText(String.valueOf(p.getAccess()));
        sAComboBox.setSelectedIndex(p.getAccess());
        sNField.setText(p.getName());

    }

    public void Delete() {

        Account p = new Account(sUField.getText(),
                spassField.getText(),
                sAComboBox.getSelectedIndex(),
                sNField.getText());

        if (AccountController.DeleteUser(p)) {
            ListElement element = new ListElement(p.getUsername(),
                    p.getPassword(),
                    p.getAccess(),
                    p.getName());
            UpdateList(REMOVE, element);

            errLabel.setForeground(Color.blue);
            errLabel.setText("User deleted successfully");

            setSearchValuesToNull();
            setSearchFieldsEditable(false);

            deleteButton.setEnabled(false);
            editButton.setEnabled(false);
            submitButton.setEnabled(false);
        }
    }

    public void Edit() {
        String username = sUField.getText();
        String password = spassField.getText();
        String access = String.valueOf(sAComboBox.getSelectedIndex());
        String name = sNField.getText();

        setSearchFieldsEditable(true);

        submitButton.setEnabled(true);
        editButton.setEnabled(false);
        deleteButton.setEnabled(false);

        temp = new Account(username, password, Integer.valueOf(access), name);
    }

    public void Submit() {
        String username = sUField.getText();
        String password = spassField.getText();
        String access = String.valueOf(sAComboBox.getSelectedIndex());
        String name = sNField.getText();

        errLabel.setForeground(Color.blue);
        errLabel.setText("User edited successfully");

        setSearchFieldsEditable(false);

        Account p = new Account(username, password, Integer.valueOf(access), name);

        AccountController.DeleteUser(temp);
        AccountController.AddUser(p);

        ListElement t = new ListElement(temp.getUsername(), temp.getPassword(),
                temp.getAccess(), temp.getName());
        ListElement q = new ListElement(username, password, Integer.valueOf(access), name);

        UpdateList(REMOVE, t);
        UpdateList(ADD, q);

        deleteButton.setEnabled(false);
        editButton.setEnabled(false);
        submitButton.setEnabled(false);

        list.setSelectedIndex(list.getLastVisibleIndex());
        Search(users.getElementAt(users.getSize() - 1).username);

    }

    public boolean aCheck() {
        boolean flag = true;

        // preconditions
        errLabel.setForeground(Color.red);
        asetAllForeground(Color.black);

        // Username
        // if it is either nothing or default, throw error
        // if it contains separator character, throw error
        if (aUField.getText().equals("") || aUField.getText().equals("--")) {
            flag = false;
            aUField.setText("--");
            aUField.setForeground(Color.red);
        } else if (!Util.sepCheck(aUField.getText())) {
            flag = false;
            aUField.setForeground(Color.red);
        }

        // Password
        // if it is nothing, throw error
        // if it contains separator character, throw error
        if (apassField.getText().equals("") && aconfirmpassField.getText().equals("")) {
            flag = false;
            apassField.setForeground(Color.red);
            aconfirmpassField.setForeground(Color.red);
        } else if (!apasswordsMatch) {
            flag = false;
            apassField.setForeground(Color.red);
            aconfirmpassField.setForeground(Color.red);
        } else if (!Util.sepCheck(apassField.getText())) {
            flag = false;
            apassField.setForeground(Color.red);
            aconfirmpassField.setForeground(Color.red);
        }

        // Access
        // if the box is on the default index, throw error
        if (aAComboBox.getSelectedIndex() == 3) {
            flag = false;
            aAComboBox.setForeground(Color.red);
        }

        // Name
        // if it is either nothing or the default, throw error
        if (aNField.getText().equals("") || aNField.getText().equals("--")) {
            flag = false;
            aNField.setText("--");
            aNField.setForeground(Color.red);
        }

        setAddErrLabel();
        return flag;
    }

    public boolean sCheck() {
        boolean flag = true;

        // preconditions
        errLabel.setForeground(Color.red);
        ssetAllForeground(Color.black);

        // Username
        // if it is either nothing or default, throw error
        // if it contains separator character, throw error
        if (sUField.getText().equals("") || sUField.getText().equals("--")) {
            flag = false;
            sUField.setText("--");
            sUField.setForeground(Color.red);
        } else if (!Util.sepCheck(sUField.getText())) {
            flag = false;
            sUField.setForeground(Color.red);
        }

        // Password
        // if it is nothing, throw error
        // if it contains separator character, throw error
        if (spassField.getText().equals("") && sconfirmpassField.getText().equals("")) {
            flag = false;
            spassField.setForeground(Color.red);
            sconfirmpassField.setForeground(Color.red);
        } else if (!spasswordsMatch) {
            flag = false;
            spassField.setForeground(Color.red);
            sconfirmpassField.setForeground(Color.red);
        } else if (!Util.sepCheck(spassField.getText())) {
            flag = false;
            spassField.setForeground(Color.red);
            sconfirmpassField.setForeground(Color.red);
        }

        // Access
        // if the box is on the default index, throw error
        if (sAComboBox.getSelectedIndex() == 3) {
            flag = false;
            sAComboBox.setForeground(Color.red);
        }

        // Name
        // if it is either nothing or the default, throw error
        if (sNField.getText().equals("") || sNField.getText().equals("--")) {
            flag = false;
            sNField.setText("--");
            sNField.setForeground(Color.red);
        }

        setSearchErrLabel();
        return flag;
    }

    public void setAddErrLabel() {
        int errCount = 0;
        String err = "";

        if (aNField.getForeground() == Color.red) {
            errCount++;
            err = "Error with name field";
        }

        if (aAComboBox.getForeground() == Color.red) {
            errCount++;
            err = "Error with access field";
        }

        if (apassField.getForeground() == Color.red
                && aconfirmpassField.getForeground() == Color.red) {
            errCount++;
            err = "Error with password field(s)";
        }

        if (aUField.getForeground() == Color.red) {
            errCount++;
            err = "Error with username field";
        }

        if (errCount > 1) {
            errLabel.setForeground(Color.red);
            errLabel.setText(err + " and " + (errCount - 1) + " other(s)");
        } else if (errCount == 1) {
            errLabel.setForeground(Color.red);
            errLabel.setText(err);
        }
    }

    public void setSearchErrLabel() {
        int errCount = 0;
        String err = "";

        if (sNField.getForeground() == Color.red) {
            errCount++;
            err = "Error with name field";
        }

        if (sAComboBox.getForeground() == Color.red) {
            errCount++;
            err = "Error with access field";
        }

        if (spassField.getForeground() == Color.red
                && sconfirmpassField.getForeground() == Color.red) {
            errCount++;
            err = "Error with password field(s)";
        }

        if (sUField.getForeground() == Color.red) {
            errCount++;
            err = "Error with username field";
        }

        if (errCount > 1) {
            errLabel.setForeground(Color.red);
            errLabel.setText(err + " and " + (errCount - 1) + " other(s)");
        } else if (errCount == 1) {
            errLabel.setForeground(Color.red);
            errLabel.setText(err);
        }
    }

    public void asetAllForeground(Color c) {
        aAComboBox.setForeground(c);
        aNField.setForeground(c);
        aUField.setForeground(c);
        apassField.setForeground(c);
        aconfirmpassField.setForeground(c);
    }

    public void ssetAllForeground(Color c) {
        sAComboBox.setForeground(c);
        sNField.setForeground(c);
        sUField.setForeground(c);
        spassField.setForeground(c);
        sconfirmpassField.setForeground(c);
    }

    public void aCheckPasswordMatch() {
        if (apassField.getText().equals(aconfirmpassField.getText())) {
            apasswordMatch.setForeground(Color.blue);
            apasswordMatch.setText("Passwords match!");
            apasswordsMatch = true;
        } else {
            apasswordMatch.setForeground(Color.red);
            apasswordMatch.setText("Passwords don't match!");
            apasswordsMatch = false;
        }
    }

    public void sCheckPasswordMatch() {
        if (spassField.getText().equals(sconfirmpassField.getText())) {
            spasswordMatch.setForeground(Color.blue);
            spasswordMatch.setText("Passwords match!");
            spasswordsMatch = true;
        } else {
            spasswordMatch.setForeground(Color.red);
            spasswordMatch.setText("Passwords don't match!");
            spasswordsMatch = false;
        }
    }

    public void setAddValuesToNull() {
        aUField.setText("");
        apassField.setText("");
        aconfirmpassField.setText("");
        aNField.setText("");
        apasswordMatch.setText(" ");
        aAComboBox.setSelectedIndex(3);
    }

    public void setSearchValuesToNull() {
        sUField.setText("");
        spassField.setText("");
        sconfirmpassField.setText("");
        spasswordMatch.setText(" ");
        sAComboBox.setSelectedIndex(3);
        sshowPassword.setEnabled(false);
        sAField.setText("");
        sNField.setText("");

        sUField.setBackground(new Color(240, 240, 240));
        spassField.setBackground(new Color(240, 240, 240));
        sconfirmpassField.setBackground(new Color(240, 240, 240));
        sAField.setBackground(new Color(240, 240, 240));
        sNField.setBackground(new Color(240, 240, 240));
    }

    public void setSearchFieldsToValid() {
        sAField.setEnabled(true);
        sshowPassword.setEnabled(true);
        sUField.setBackground(Color.white);
        spassField.setBackground(Color.white);
        sconfirmpassField.setBackground(Color.white);
        sAField.setBackground(Color.white);
        sNField.setBackground(Color.white);
    }

    public void setSearchFieldsEditable(boolean b) {
        sUField.setEditable(b);
        spassField.setEditable(b);
        sconfirmpassField.setEditable(b);
        sAComboBox.setEnabled(b);
        sNField.setEditable(b);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AccountGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L10;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JComboBox<String> aAComboBox;
    private javax.swing.JTextField aAField;
    private javax.swing.JTextField aNField;
    private javax.swing.JTextField aUField;
    private javax.swing.JPasswordField aconfirmpassField;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JPasswordField apassField;
    private javax.swing.JLabel apasswordMatch;
    private javax.swing.JLabel ashowPassword;
    private javax.swing.JMenuItem bugItem;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel errLabel;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JList<String> list;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JComboBox<String> sAComboBox;
    private javax.swing.JTextField sAField;
    private javax.swing.JTextField sNField;
    private javax.swing.JTextField sUField;
    private javax.swing.JPasswordField sconfirmpassField;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JPasswordField spassField;
    private javax.swing.JLabel spasswordMatch;
    private javax.swing.JLabel sshowPassword;
    private javax.swing.JButton submitButton;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
