/**
 * Not fully implmented yet
 */
package webradio;

import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

public class FinanceGUI extends javax.swing.JFrame {

    /**
     * Minor inner class used to limit th amount of text in a text field
     */
    // <editor-fold defaultstate="collapsed" desc="JTextFieldLimit">
    class JTextFieldLimit extends PlainDocument {

        private final int limit;

        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }

        JTextFieldLimit(int limit, boolean upper) {
            super();
            this.limit = limit;
        }

        @Override
        public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
            if (str == null) {
                return;
            }

            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }
    // </editor-fold>
    
    DecimalFormat money = new DecimalFormat("0.00");
    double pennies;
    double nickels;
    double dimes;
    double quarters;
    double halfdollars;
    double dollarcoins;
    double dollars;
    double fives;
    double tens;
    double twenties;
    double fifties;
    double hundreds;
    
    /**
     * Creates new form FinanceGUI
     */
    public FinanceGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        moneycounterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pennyL = new javax.swing.JLabel();
        nickelL = new javax.swing.JLabel();
        dimeL = new javax.swing.JLabel();
        quarterL = new javax.swing.JLabel();
        halfdollarL = new javax.swing.JLabel();
        dollarcoinL = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totalL = new javax.swing.JLabel();
        pennySpinner = new javax.swing.JSpinner();
        nickelSpinner = new javax.swing.JSpinner();
        dimeSpinner = new javax.swing.JSpinner();
        quarterSpinner = new javax.swing.JSpinner();
        halfdollarSpinner = new javax.swing.JSpinner();
        dollarcoinSpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        dollarSpinner = new javax.swing.JSpinner();
        dollarL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fiveSpinner = new javax.swing.JSpinner();
        fiveL = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tenSpinner = new javax.swing.JSpinner();
        tenL = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        twentySpinner = new javax.swing.JSpinner();
        twentyL = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fiftySpinner = new javax.swing.JSpinner();
        fiftyL = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        hundredSpinner = new javax.swing.JSpinner();
        hundredL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        errLabel = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        closeItem = new javax.swing.JMenuItem();
        logoutItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        helpItem = new javax.swing.JMenuItem();
        bugItem = new javax.swing.JMenuItem();
        suggestionItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon("src\\images\\imageicon.png").getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        moneycounterPanel.setName("Funds Calc"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Amount");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Pennies:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Nickels:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Dimes:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Quarters:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Half Dollars:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Dollar Coins:");

        pennyL.setText("$0.00");

        nickelL.setText("$0.00");

        dimeL.setText("$0.00");

        quarterL.setText("$0.00");

        halfdollarL.setText("$0.00");

        dollarcoinL.setText("$0.00");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Total:");

        totalL.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalL.setText("$0.00");

        pennySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        pennySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pennySpinnerStateChanged(evt);
            }
        });

        nickelSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        nickelSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nickelSpinnerStateChanged(evt);
            }
        });

        dimeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        dimeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dimeSpinnerStateChanged(evt);
            }
        });

        quarterSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        quarterSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quarterSpinnerStateChanged(evt);
            }
        });

        halfdollarSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        halfdollarSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                halfdollarSpinnerStateChanged(evt);
            }
        });

        dollarcoinSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        dollarcoinSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dollarcoinSpinnerStateChanged(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Dollars:");

        dollarSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        dollarSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                dollarSpinnerStateChanged(evt);
            }
        });

        dollarL.setText("$0.00");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Fives:");

        fiveSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        fiveSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiveSpinnerStateChanged(evt);
            }
        });

        fiveL.setText("$0.00");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Tens:");

        tenSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        tenSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tenSpinnerStateChanged(evt);
            }
        });

        tenL.setText("$0.00");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Twenties:");

        twentySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        twentySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                twentySpinnerStateChanged(evt);
            }
        });

        twentyL.setText("$0.00");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel12.setText("Fifties:");

        fiftySpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        fiftySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fiftySpinnerStateChanged(evt);
            }
        });

        fiftyL.setText("$0.00");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Hundreds:");

        hundredSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        hundredSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hundredSpinnerStateChanged(evt);
            }
        });

        hundredL.setText("$0.00");

        javax.swing.GroupLayout moneycounterPanelLayout = new javax.swing.GroupLayout(moneycounterPanel);
        moneycounterPanel.setLayout(moneycounterPanelLayout);
        moneycounterPanelLayout.setHorizontalGroup(
            moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moneycounterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moneycounterPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pennySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nickelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quarterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(halfdollarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dollarcoinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dollarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twentySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiftySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hundredSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dimeL, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(quarterL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(halfdollarL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dollarcoinL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(moneycounterPanelLayout.createSequentialGroup()
                                    .addComponent(pennyL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(nickelL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(dollarL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twentyL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiftyL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hundredL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(moneycounterPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        moneycounterPanelLayout.setVerticalGroup(
            moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moneycounterPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalL)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pennyL)
                    .addComponent(pennySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nickelL)
                    .addComponent(nickelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dimeL)
                    .addComponent(dimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(quarterL)
                    .addComponent(quarterSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(halfdollarL)
                    .addComponent(halfdollarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dollarcoinL)
                    .addComponent(dollarcoinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dollarSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dollarL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fiveSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiveL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(twentySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twentyL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fiftySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiftyL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moneycounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(hundredSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hundredL))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funds Calculator", moneycounterPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        errLabel.setText(" ");

        file.setText("File");

        closeItem.setText("Close");
        closeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeItemActionPerformed(evt);
            }
        });
        file.add(closeItem);

        logoutItem.setText("Logout");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        file.add(logoutItem);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        file.add(exitItem);

        menubar.add(file);

        help.setText("Help");

        helpItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        helpItem.setText("Open Help...");
        helpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpItemActionPerformed(evt);
            }
        });
        help.add(helpItem);

        bugItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bug_PNG3980.png"))); // NOI18N
        bugItem.setText("Report a bug");
        bugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugItemActionPerformed(evt);
            }
        });
        help.add(bugItem);

        suggestionItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        suggestionItem.setText("Make a suggestion");
        suggestionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestionItemActionPerformed(evt);
            }
        });
        help.add(suggestionItem);

        menubar.add(help);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Main.CloseFinanceGUI();
    }//GEN-LAST:event_formWindowClosed

    private void closeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeItemActionPerformed
        Main.CloseProfileGUI();
    }//GEN-LAST:event_closeItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        Main.Logout();
        Main.CloseProfileGUI();
        Main.CloseMainGUI();
    }//GEN-LAST:event_logoutItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        int res = JOptionPane.showConfirmDialog(
            null,
            "Are you sure you want to exit WRAP?",
            "",
            JOptionPane.YES_NO_OPTION);

        // do a thing based on response
        switch (res) {
            case 0:
            System.exit(0);
            break;
            default:
            // do nothing
        }
    }//GEN-LAST:event_exitItemActionPerformed

    private void helpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpItemActionPerformed
        Main.LaunchHelpGUI();
    }//GEN-LAST:event_helpItemActionPerformed

    private void bugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugItemActionPerformed
        Main.LaunchBugReportGUI();
    }//GEN-LAST:event_bugItemActionPerformed

    private void suggestionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestionItemActionPerformed
        Main.LaunchSuggestionReportGUI();
    }//GEN-LAST:event_suggestionItemActionPerformed

    private void pennySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pennySpinnerStateChanged
        pennies = Integer.valueOf(pennySpinner.getValue().toString());
        double d = pennies/100;
        pennyL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_pennySpinnerStateChanged

    private void nickelSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nickelSpinnerStateChanged
        nickels = Integer.valueOf(nickelSpinner.getValue().toString());
        double d = nickels/20;
        nickelL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_nickelSpinnerStateChanged

    private void dimeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dimeSpinnerStateChanged
        dimes = Integer.valueOf(dimeSpinner.getValue().toString());
        double d = dimes/10;
        dimeL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_dimeSpinnerStateChanged

    private void quarterSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quarterSpinnerStateChanged
        quarters = Integer.valueOf(quarterSpinner.getValue().toString());
        double d = quarters/4;
        quarterL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_quarterSpinnerStateChanged

    private void halfdollarSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_halfdollarSpinnerStateChanged
        halfdollars = Integer.valueOf(halfdollarSpinner.getValue().toString());
        double d = halfdollars/2;
        halfdollarL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_halfdollarSpinnerStateChanged

    private void dollarcoinSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dollarcoinSpinnerStateChanged
        dollarcoins = Integer.valueOf(dollarcoinSpinner.getValue().toString());
        double d = dollarcoins;
        dollarcoinL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_dollarcoinSpinnerStateChanged

    private void dollarSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_dollarSpinnerStateChanged
        dollars = Integer.valueOf(dollarSpinner.getValue().toString());
        double d = dollars;
        dollarL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_dollarSpinnerStateChanged

    private void fiveSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiveSpinnerStateChanged
        fives = Integer.valueOf(fiveSpinner.getValue().toString());
        double d = fives*5;
        fiveL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_fiveSpinnerStateChanged

    private void tenSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tenSpinnerStateChanged
        tens = Integer.valueOf(tenSpinner.getValue().toString());
        double d = tens*10;
        tenL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_tenSpinnerStateChanged

    private void twentySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_twentySpinnerStateChanged
        twenties = Integer.valueOf(twentySpinner.getValue().toString());
        double d = twenties*20;
        twentyL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_twentySpinnerStateChanged

    private void fiftySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fiftySpinnerStateChanged
        fifties = Integer.valueOf(fiftySpinner.getValue().toString());
        double d = fifties*50;
        fiftyL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_fiftySpinnerStateChanged

    private void hundredSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hundredSpinnerStateChanged
        hundreds = Integer.valueOf(hundredSpinner.getValue().toString());
        double d = hundreds*100;
        hundredL.setText("$" + money.format(d));
        updateTotal();
    }//GEN-LAST:event_hundredSpinnerStateChanged

    public void updateTotal() {

        double total = 0;
        
        total += pennies/100;
        total += nickels/20;
        total += dimes/10;
        total += quarters/4;
        total += halfdollars/2;
        total += dollarcoins;
        total += dollars;
        total += fives*5;
        total += tens*10;
        total += twenties*20;
        total += fifties*50;
        total += hundreds*100;

        
        totalL.setText("$" + money.format(total));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinanceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FinanceGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bugItem;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JLabel dimeL;
    private javax.swing.JSpinner dimeSpinner;
    private javax.swing.JLabel dollarL;
    private javax.swing.JSpinner dollarSpinner;
    private javax.swing.JLabel dollarcoinL;
    private javax.swing.JSpinner dollarcoinSpinner;
    private javax.swing.JLabel errLabel;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JLabel fiftyL;
    private javax.swing.JSpinner fiftySpinner;
    private javax.swing.JMenu file;
    private javax.swing.JLabel fiveL;
    private javax.swing.JSpinner fiveSpinner;
    private javax.swing.JLabel halfdollarL;
    private javax.swing.JSpinner halfdollarSpinner;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem helpItem;
    private javax.swing.JLabel hundredL;
    private javax.swing.JSpinner hundredSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JPanel moneycounterPanel;
    private javax.swing.JLabel nickelL;
    private javax.swing.JSpinner nickelSpinner;
    private javax.swing.JLabel pennyL;
    private javax.swing.JSpinner pennySpinner;
    private javax.swing.JLabel quarterL;
    private javax.swing.JSpinner quarterSpinner;
    private javax.swing.JMenuItem suggestionItem;
    private javax.swing.JLabel tenL;
    private javax.swing.JSpinner tenSpinner;
    private javax.swing.JLabel totalL;
    private javax.swing.JLabel twentyL;
    private javax.swing.JSpinner twentySpinner;
    // End of variables declaration//GEN-END:variables
}
