/**
 * File: HelpGUI.java
 * Desc: GUI interface for help
 *
 * Author: Pat Ripley
 */

package webradio;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeSelectionModel;
import javax.swing.ImageIcon;

public class HelpGUI extends javax.swing.JFrame {

    /** Creates new form HelpGUI */
    public HelpGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treeSP = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        textSP = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        videoButton = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        closeItem = new javax.swing.JMenuItem();
        logoutItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        links = new javax.swing.JMenu();
        webradioItem = new javax.swing.JMenuItem();
        SIUeMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        profilesMenu = new javax.swing.JMenu();
        collegiatelinkItem = new javax.swing.JMenuItem();
        facebookItem = new javax.swing.JMenuItem();
        financesMenu = new javax.swing.JMenu();
        paypalItem = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        bugItem = new javax.swing.JMenuItem();
        suggestionItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("W.R.A.P. - Help");
        setIconImage(new ImageIcon("src/images/goose.png").getImage());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("W.R.A.P.");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Profiles");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Adding a Profile");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Editing a Profile");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Deleting a Profile");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Types of Profiles");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fields (Profiles)");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Accounts");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Adding an Account");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Editing an Account");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Deleting an Account");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Types of Accounts");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fields (Accounts)");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Tasks");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Editing a Profile's tasks");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Task Descriptions");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Shows");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Adding a Show");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Editing a Show");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Deleting a Show");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fields (Shows)");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Finances");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Adding a Transaction");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Editing a Transaction");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Deleting a Transaction");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Editing Account amounts");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Using the money counter");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fields (Transactions)");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Reports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Generating reports");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeValueChanged(evt);
            }
        });
        treeSP.setViewportView(tree);

        textSP.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        textSP.setViewportView(textArea);

        videoButton.setText("Open Instructional Video");
        videoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoButtonActionPerformed(evt);
            }
        });

        file.setText("File");

        closeItem.setText("Close");
        closeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeItemActionPerformed(evt);
            }
        });
        file.add(closeItem);

        logoutItem.setText("Logout");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        file.add(logoutItem);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        file.add(exitItem);

        menubar.add(file);

        links.setText("Links");

        webradioItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imageicon.png"))); // NOI18N
        webradioItem.setText("Web Radio");
        webradioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webradioItemActionPerformed(evt);
            }
        });
        links.add(webradioItem);

        SIUeMenu.setText("SIUe");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/e.PNG"))); // NOI18N
        jMenuItem1.setText("Homepage");
        SIUeMenu.add(jMenuItem1);

        links.add(SIUeMenu);

        profilesMenu.setText("Profiles");

        collegiatelinkItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/collegiatelink.png"))); // NOI18N
        collegiatelinkItem.setText("CollegiateLink");
        collegiatelinkItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegiatelinkItemActionPerformed(evt);
            }
        });
        profilesMenu.add(collegiatelinkItem);

        facebookItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/facebook.png"))); // NOI18N
        facebookItem.setText("Facebook (Show Hosts)");
        facebookItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookItemActionPerformed(evt);
            }
        });
        profilesMenu.add(facebookItem);

        links.add(profilesMenu);

        financesMenu.setText("Finances");

        paypalItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paypal.png"))); // NOI18N
        paypalItem.setText("PayPal");
        paypalItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paypalItemActionPerformed(evt);
            }
        });
        financesMenu.add(paypalItem);

        links.add(financesMenu);

        menubar.add(links);

        help.setText("Help");

        bugItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bug_PNG3980.png"))); // NOI18N
        bugItem.setText("Report a bug");
        bugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugItemActionPerformed(evt);
            }
        });
        help.add(bugItem);

        suggestionItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        suggestionItem.setText("Make a suggestion");
        suggestionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestionItemActionPerformed(evt);
            }
        });
        help.add(suggestionItem);

        menubar.add(help);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(treeSP, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textSP, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(videoButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(videoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(treeSP, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(textSP))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Handles when user chooses close option in the menu bar
     */
    private void closeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeItemActionPerformed
        Main.CloseAccountGUI();
    }//GEN-LAST:event_closeItemActionPerformed

    /**
     * Handles when user chooses logout option in the menu bar
     */
    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        Main.Logout();
        Main.CloseAccountGUI();
        Main.CloseMainGUI();
    }//GEN-LAST:event_logoutItemActionPerformed

    /**
     * Handles when user chooses exit option in the menu bar
     */
    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        int res = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to exit WRAP?",
                "",
                JOptionPane.YES_NO_OPTION);

        // do a thing based on response
        switch (res) {
            case 0:
                System.exit(0);
                break;
            default:
            // do nothing
        }
    }//GEN-LAST:event_exitItemActionPerformed

    /**
     * Handles when user chooses "Report a Bug" option in the menu bar
     */
    private void bugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugItemActionPerformed
        Main.LaunchBugReportGUI();
    }//GEN-LAST:event_bugItemActionPerformed

    /**
     * Handles when user chooses "Make Suggestion" option in the menu bar
     */
    private void suggestionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestionItemActionPerformed
        Main.LaunchSuggestionReportGUI();
    }//GEN-LAST:event_suggestionItemActionPerformed

    /**
     * Handles when user closes window
     */
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Main.CloseHelpGUI();
    }//GEN-LAST:event_formWindowClosed

    /**
     * Handles when user clicks on different options in the tree
     * @param evt 
     */
    private void treeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeValueChanged
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) tree.getLastSelectedPathComponent();

        if (node == null) {
            // nothing is selected
            return;
        }

        Object nodeInfo = node.getUserObject();
        String s = nodeInfo.toString();

        switch (s) {
            case "Profiles":
                textArea.setText(HelpController.getProfiles());
                break;
            case "Adding a Profile":
                textArea.setText(HelpController.getAddProfile());
                break;
            case "Editing a Profile":
                textArea.setText(HelpController.getEditProfile());
                break;
            case "Deleting a Profile":
                textArea.setText(HelpController.getDeleteProfile());
                break;
            case "Types of Profiles":
                textArea.setText(HelpController.getProfileTypes());
                break;
            case "Fields (Profiles)":
                textArea.setText(HelpController.getFieldsProfiles());
                break;
            case "Accounts":
                textArea.setText(HelpController.getAccounts());
                break;
            case "Adding an Account":
                textArea.setText(HelpController.getAddAccount());
                break;
            case "Editing an Account":
                textArea.setText(HelpController.getEditAccount());
                break;
            case "Deleting an Account":
                textArea.setText(HelpController.getDeleteAccount());
                break;
            case "Types of Accounts":
                textArea.setText(HelpController.getAccountType());
                break;
            case "Fields (Accounts)":
                textArea.setText(HelpController.getFieldsAccounts());
                break;
            case "Tasks":
                textArea.setText(HelpController.getTasks());
                break;
            case "Editing a Profile's tasks":
                textArea.setText(HelpController.getEditTasks());
                break;
            case "Task Descriptions":
                textArea.setText(HelpController.getTaskDesctriptions());
                break;
            case "Shows":
                textArea.setText(HelpController.getShows());
                break;
            case "Adding a Show":
                textArea.setText(HelpController.getAddShow());
                break;
            case "Editing a Show":
                textArea.setText(HelpController.getEditShow());
                break;
            case "Deleting a Show":
                textArea.setText(HelpController.getDeleteShow());
                break;
            case "Fields (Shows)":
                textArea.setText(HelpController.getFieldsShows());
                break;
            case "Finances":
                textArea.setText(HelpController.getFinances());
                break;
            case "Adding a Transaction":
                textArea.setText(HelpController.getAddTransaction());
                break;
            case "Editing a Transaction":
                textArea.setText(HelpController.getEditTransaction());
                break;
            case "Deleting a Transaction":
                textArea.setText(HelpController.getDeleteTransaction());
                break;
            case "Editing Account amounts":
                textArea.setText(HelpController.getAccountAmounts());
                break;
            case "Using the money counter":
                textArea.setText(HelpController.getMoneyCounter());
                break;
            case "Fields (Transactions)":
                textArea.setText(HelpController.getFieldsTransactions());
                break;
            case "Reports":
                textArea.setText(HelpController.getReports());
                break;
            case "Generating reports":
                textArea.setText(HelpController.getGeneratingReports());
                break;
            default:
                break;
        }
    }//GEN-LAST:event_treeValueChanged

    /**
     * Handles when user clicks on "Open Instructional Video" 
     * Opens video in local default video player
     * @param evt 
     */
    private void videoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoButtonActionPerformed
        try {
            Desktop.getDesktop().open(new File("src\\dugs.mp4"));
        } catch (IOException ex) {
            Util.error(ex.toString(), ex.getMessage());
        }
    }//GEN-LAST:event_videoButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // log
            EventLog.add("opened help");
    }//GEN-LAST:event_formComponentShown

    private void webradioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webradioItemActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.siue.edu/webradio"));
        } catch (IOException | URISyntaxException ex) {
            Util.error(ex.toString(), ex.getMessage());
        }
    }//GEN-LAST:event_webradioItemActionPerformed

    private void collegiatelinkItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegiatelinkItemActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://siue.collegiatelink.net/organization/webradio"));
        } catch (IOException | URISyntaxException ex) {
            Util.error(ex.toString(), ex.getMessage());
        }
    }//GEN-LAST:event_collegiatelinkItemActionPerformed

    private void facebookItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookItemActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.facebook.com/groups/156451584405369/"));
        } catch (IOException | URISyntaxException ex) {
            Util.error(ex.toString(), ex.getMessage());
        }
    }//GEN-LAST:event_facebookItemActionPerformed

    private void paypalItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paypalItemActionPerformed
        try {
            Desktop.getDesktop().browse(new URI("https://www.paypal.com/businessexp/summary"));
        } catch (IOException | URISyntaxException ex) {
            Util.error(ex.toString(), ex.getMessage());
        }
    }//GEN-LAST:event_paypalItemActionPerformed

    /**
     * main()
     *
     * You already know what main is if you're reading this
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Util.error(ex.toString(), ex.getMessage());
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HelpGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SIUeMenu;
    private javax.swing.JMenuItem bugItem;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JMenuItem collegiatelinkItem;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenuItem facebookItem;
    private javax.swing.JMenu file;
    private javax.swing.JMenu financesMenu;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu links;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem paypalItem;
    private javax.swing.JMenu profilesMenu;
    private javax.swing.JMenuItem suggestionItem;
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textSP;
    private javax.swing.JTree tree;
    private javax.swing.JScrollPane treeSP;
    private javax.swing.JButton videoButton;
    private javax.swing.JMenuItem webradioItem;
    // End of variables declaration//GEN-END:variables
}
