/**
 * File: ProfileGUI.java
 * Desc: Sends input to ReportsController and handles all the GUI related events
 *
 * Author: Pat Ripley
 */
package webradio;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

public class ReportsGUI extends javax.swing.JFrame {
    
    File f;
    
    /**
     * Creates new form ReportsGUI
     */
    public ReportsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        adminLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        errLabel = new javax.swing.JLabel();
        generateButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        profilesRadio = new javax.swing.JRadioButton();
        accountsRadio = new javax.swing.JRadioButton();
        tasksRadio = new javax.swing.JRadioButton();
        showsRadio = new javax.swing.JRadioButton();
        financesRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        profilesTypeBox = new javax.swing.JComboBox<>();
        accountsTypeBox = new javax.swing.JComboBox<>();
        tasksTypeBox = new javax.swing.JComboBox<>();
        showsTypeBox = new javax.swing.JComboBox<>();
        financesTypeBox = new javax.swing.JComboBox<>();
        profilesSortByBox = new javax.swing.JComboBox<>();
        accountsSortByBox = new javax.swing.JComboBox<>();
        tasksSortByBox = new javax.swing.JComboBox<>();
        showsSortByBox = new javax.swing.JComboBox<>();
        financesSortByBox = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        closeItem = new javax.swing.JMenuItem();
        logoutItem = new javax.swing.JMenuItem();
        exitItem = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        helpItem = new javax.swing.JMenuItem();
        bugItem = new javax.swing.JMenuItem();
        suggestionItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("W.R.A.P. - Reports");
        setIconImage(new ImageIcon("src\\images\\goose.png").getImage());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        adminLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        adminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminLabelMouseExited(evt);
            }
        });

        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        loginLabel.setText(" ");
        loginLabel.setToolTipText("");

        errLabel.setForeground(new java.awt.Color(255, 0, 0));
        errLabel.setText(" ");

        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        openButton.setText("Open");
        openButton.setEnabled(false);
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        group.add(profilesRadio);
        profilesRadio.setText("Profiles");
        profilesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilesRadioActionPerformed(evt);
            }
        });

        group.add(accountsRadio);
        accountsRadio.setText("Accounts");
        accountsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountsRadioActionPerformed(evt);
            }
        });

        group.add(tasksRadio);
        tasksRadio.setText("Tasks");
        tasksRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksRadioActionPerformed(evt);
            }
        });

        group.add(showsRadio);
        showsRadio.setText("Shows");
        showsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showsRadioActionPerformed(evt);
            }
        });

        group.add(financesRadio);
        financesRadio.setText("Finances");
        financesRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                financesRadioActionPerformed(evt);
            }
        });

        jLabel1.setText("Report:");

        jLabel2.setText("Type:");

        jLabel3.setText("Sort by:");

        profilesTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Simple", "Contact", "Full" }));
        profilesTypeBox.setEnabled(false);

        accountsTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Simple", "Full" }));
        accountsTypeBox.setEnabled(false);

        tasksTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Dues", "Trained", "Paperwork", "Show Desc/Time", "Full" }));
        tasksTypeBox.setEnabled(false);

        showsTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Simple", "Full" }));
        showsTypeBox.setEnabled(false);

        financesTypeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Transactions", "Full" }));
        financesTypeBox.setEnabled(false);

        profilesSortByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Last Name", "First Name", "Type", "Position" }));
        profilesSortByBox.setEnabled(false);

        accountsSortByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Username", "Access" }));
        accountsSortByBox.setEnabled(false);

        tasksSortByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Last Name", "Dues", "Trained", "Paperwork", "ShowDesc/Time" }));
        tasksSortByBox.setEnabled(false);

        showsSortByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Show Name", "Day" }));
        showsSortByBox.setEnabled(false);

        financesSortByBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Date", "Amount" }));
        financesSortByBox.setEnabled(false);

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Notepad");
        jRadioButton1.setEnabled(false);

        jRadioButton2.setText("Excel");
        jRadioButton2.setEnabled(false);

        jLabel4.setText("Output:");

        file.setText("File");

        closeItem.setText("Close");
        closeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeItemActionPerformed(evt);
            }
        });
        file.add(closeItem);

        logoutItem.setText("Logout");
        logoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutItemActionPerformed(evt);
            }
        });
        file.add(logoutItem);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        file.add(exitItem);

        menubar.add(file);

        help.setText("Help");

        helpItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N
        helpItem.setText("Open Help...");
        helpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpItemActionPerformed(evt);
            }
        });
        help.add(helpItem);

        bugItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bug_PNG3980.png"))); // NOI18N
        bugItem.setText("Report a bug");
        bugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugItemActionPerformed(evt);
            }
        });
        help.add(bugItem);

        suggestionItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gear.png"))); // NOI18N
        suggestionItem.setText("Make a suggestion");
        suggestionItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestionItemActionPerformed(evt);
            }
        });
        help.add(suggestionItem);

        menubar.add(help);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(adminLabel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showsRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tasksRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(accountsRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                        .addComponent(profilesRadio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(financesRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(accountsTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(profilesTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tasksTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(showsTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(financesTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountsSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profilesSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tasksSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showsSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(financesSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilesRadio)
                    .addComponent(profilesTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profilesSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountsRadio)
                    .addComponent(accountsTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountsSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tasksRadio)
                    .addComponent(tasksSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasksTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showsRadio)
                    .addComponent(showsTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showsSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(financesRadio)
                    .addComponent(financesTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(financesSortByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generateButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton2)
                            .addComponent(openButton)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Main.CloseReportsGUI();
    }//GEN-LAST:event_formWindowClosed

    private void closeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeItemActionPerformed
        Main.CloseAccountGUI();
    }//GEN-LAST:event_closeItemActionPerformed

    private void logoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutItemActionPerformed
        Main.Logout();
        Main.CloseAccountGUI();
        Main.CloseMainGUI();
    }//GEN-LAST:event_logoutItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        int res = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to exit WRAP?",
                "",
                JOptionPane.YES_NO_OPTION);

        // do a thing based on response
        switch (res) {
            case 0:
                System.exit(0);
                break;
            default:
            // do nothing
        }
    }//GEN-LAST:event_exitItemActionPerformed

    private void bugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugItemActionPerformed
        Main.LaunchBugReportGUI();
    }//GEN-LAST:event_bugItemActionPerformed

    private void suggestionItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestionItemActionPerformed
        Main.LaunchSuggestionReportGUI();
    }//GEN-LAST:event_suggestionItemActionPerformed

    private void adminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLabelMouseClicked
        // probably some admin stuff
        JOptionPane.showMessageDialog(this,
                "Administration features\nNot implemented yet",
                "Advanced",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_adminLabelMouseClicked

    private void adminLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLabelMouseEntered
        loginLabel.setText("Advanced options");
    }//GEN-LAST:event_adminLabelMouseEntered

    private void adminLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLabelMouseExited
        loginLabel.setText("Logged in as " + Main.p.getUsername());
    }//GEN-LAST:event_adminLabelMouseExited

    /**
     * Handles when the generate button is pressed
     * @param evt 
     */
    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        generate();
    }//GEN-LAST:event_generateButtonActionPerformed

    /**
     * Handles when profiles radio button is selected
     * @param evt 
     */
    private void profilesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilesRadioActionPerformed
        updateSelection();
    }//GEN-LAST:event_profilesRadioActionPerformed

    /**
     * Handles when accounts radio button is selected
     * @param evt 
     */
    private void accountsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountsRadioActionPerformed
        updateSelection();
    }//GEN-LAST:event_accountsRadioActionPerformed

    /**
     * Handles when tasks radio button is selected
     * @param evt 
     */
    private void tasksRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksRadioActionPerformed
        updateSelection();
    }//GEN-LAST:event_tasksRadioActionPerformed

    /**
     * Handles when shows radio button is selected
     * @param evt 
     */
    private void showsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showsRadioActionPerformed
        updateSelection();
    }//GEN-LAST:event_showsRadioActionPerformed

    /**
     * Handles when finances radio button is selected
     * @param evt 
     */
    private void financesRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_financesRadioActionPerformed
        updateSelection();
    }//GEN-LAST:event_financesRadioActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        loginLabel.setText("Logged in as " + Main.p.getUsername());
    }//GEN-LAST:event_formComponentShown

    private void helpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpItemActionPerformed
        Main.LaunchHelpGUI();
    }//GEN-LAST:event_helpItemActionPerformed

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        try {
            Desktop.getDesktop().edit(f);
        } catch (IOException ex) {
            System.err.println(ex);
        }
    }//GEN-LAST:event_openButtonActionPerformed

    /**
     * generate()
     * 
     * Sends a signal to ReportsController based on type and sort by vars
     */
    public void generate() {
        
        // graphics update
        errLabel.setForeground(Color.blue);
        errLabel.setText("Generating report...");
        
        // send it to ReportsController
        if (profilesRadio.isSelected()) {
            f = ReportsController.profiles(profilesTypeBox.getSelectedIndex(), profilesSortByBox.getSelectedIndex());
            if (f != null) {
                errLabel.setForeground(Color.blue);
                errLabel.setText("Profiles report generated successfully");
                openButton.setEnabled(true);
            } else {
                errLabel.setForeground(Color.red);
                errLabel.setText("Profiles report generation failed");
                openButton.setEnabled(false);
            }
                
        } else if (accountsRadio.isSelected()) {
            f = ReportsController.accounts(accountsTypeBox.getSelectedIndex(), accountsSortByBox.getSelectedIndex());
            if (f != null) {
                errLabel.setForeground(Color.blue);
                errLabel.setText("Accounts report generated successfully");
                openButton.setEnabled(true);
            } else {
                errLabel.setForeground(Color.red);
                errLabel.setText("Accounts report generation failed");
                openButton.setEnabled(false);
            }
            
        } else if (tasksRadio.isSelected()) {
            f = ReportsController.tasks(tasksTypeBox.getSelectedIndex(), tasksSortByBox.getSelectedIndex());
            if (f != null) {
                errLabel.setForeground(Color.blue);
                errLabel.setText("Tasks report generated successfully");
                openButton.setEnabled(true);
            } else {
                errLabel.setForeground(Color.red);
                errLabel.setText("Tasks report generation failed");
                openButton.setEnabled(false);
            }
            
        } else if (showsRadio.isSelected()) {
            f = ReportsController.shows(showsTypeBox.getSelectedIndex(), showsSortByBox.getSelectedIndex());
            if(f != null) {
                errLabel.setForeground(Color.blue);
                errLabel.setText("Shows report generated successfully");
                openButton.setEnabled(true);
            } else {
                errLabel.setForeground(Color.red);
                errLabel.setText("Shows report generation failed");
                openButton.setEnabled(false);
            }
        } else if (financesRadio.isSelected()) {
            f = ReportsController.finances(financesTypeBox.getSelectedIndex(), financesSortByBox.getSelectedIndex());
            if(f != null) {
                errLabel.setForeground(Color.blue);
                errLabel.setText("Finances report generated successfully");
                openButton.setEnabled(true);
            } else {
                errLabel.setForeground(Color.red);
                errLabel.setText("Finances report generation failed");
                openButton.setEnabled(false);
            }
        }
    }
    
    /**
     * updateSelection()
     * 
     * Graphics update
     */
    public void updateSelection() {
        if (profilesRadio.isSelected()) {
            profilesTypeBox.setEnabled(true);
            profilesSortByBox.setEnabled(true);
            accountsTypeBox.setEnabled(false);
            accountsSortByBox.setEnabled(false);
            tasksTypeBox.setEnabled(false);
            tasksSortByBox.setEnabled(false);
            showsTypeBox.setEnabled(false);
            showsSortByBox.setEnabled(false);
            financesTypeBox.setEnabled(false);
            financesSortByBox.setEnabled(false);
        } else if (accountsRadio.isSelected()) {
            profilesTypeBox.setEnabled(false);
            profilesSortByBox.setEnabled(false);
            accountsTypeBox.setEnabled(true);
            accountsSortByBox.setEnabled(true);
            tasksTypeBox.setEnabled(false);
            tasksSortByBox.setEnabled(false);
            showsTypeBox.setEnabled(false);
            showsSortByBox.setEnabled(false);
            financesTypeBox.setEnabled(false);
            financesSortByBox.setEnabled(false);
        } else if (tasksRadio.isSelected()) {
            profilesTypeBox.setEnabled(false);
            profilesSortByBox.setEnabled(false);
            accountsTypeBox.setEnabled(false);
            accountsSortByBox.setEnabled(false);
            tasksTypeBox.setEnabled(true);
            tasksSortByBox.setEnabled(true);
            showsTypeBox.setEnabled(false);
            showsSortByBox.setEnabled(false);
            financesTypeBox.setEnabled(false);
            financesSortByBox.setEnabled(false);
        } else if (showsRadio.isSelected()) {
            profilesTypeBox.setEnabled(false);
            profilesSortByBox.setEnabled(false);
            accountsTypeBox.setEnabled(false);
            accountsSortByBox.setEnabled(false);
            tasksTypeBox.setEnabled(false);
            tasksSortByBox.setEnabled(false);
            showsTypeBox.setEnabled(true);
            showsSortByBox.setEnabled(true);
            financesTypeBox.setEnabled(false);
            financesSortByBox.setEnabled(false);
        } else if (financesRadio.isSelected()) {
            profilesTypeBox.setEnabled(false);
            profilesSortByBox.setEnabled(false);
            accountsTypeBox.setEnabled(false);
            accountsSortByBox.setEnabled(false);
            tasksTypeBox.setEnabled(false);
            tasksSortByBox.setEnabled(false);
            showsTypeBox.setEnabled(false);
            showsSortByBox.setEnabled(false);
            financesTypeBox.setEnabled(true);
            financesSortByBox.setEnabled(true);
        }
    }

    /**
     * main()
     * 
     * You already know what main is if you're reading this
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReportsGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton accountsRadio;
    private javax.swing.JComboBox<String> accountsSortByBox;
    private javax.swing.JComboBox<String> accountsTypeBox;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JMenuItem bugItem;
    private javax.swing.JMenuItem closeItem;
    private javax.swing.JLabel errLabel;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu file;
    private javax.swing.JRadioButton financesRadio;
    private javax.swing.JComboBox<String> financesSortByBox;
    private javax.swing.JComboBox<String> financesTypeBox;
    private javax.swing.JButton generateButton;
    private javax.swing.ButtonGroup group;
    private javax.swing.JMenu help;
    private javax.swing.JMenuItem helpItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JMenuItem logoutItem;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JButton openButton;
    private javax.swing.JRadioButton profilesRadio;
    private javax.swing.JComboBox<String> profilesSortByBox;
    private javax.swing.JComboBox<String> profilesTypeBox;
    private javax.swing.JRadioButton showsRadio;
    private javax.swing.JComboBox<String> showsSortByBox;
    private javax.swing.JComboBox<String> showsTypeBox;
    private javax.swing.JMenuItem suggestionItem;
    private javax.swing.JRadioButton tasksRadio;
    private javax.swing.JComboBox<String> tasksSortByBox;
    private javax.swing.JComboBox<String> tasksTypeBox;
    // End of variables declaration//GEN-END:variables
}
